## Problem Statement
In this assignment students will build the random forest model after normalizing the
variable to house pricing from boston data set.
Following the code to get data into the environment:

In [157]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import datasets
from sklearn import preprocessing
from sklearn import utils

In [158]:
boston = datasets.load_boston()

In [159]:
boston

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
         4.9800e+00],
        [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
         9.1400e+00],
        [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
         4.0300e+00],
        ...,
        [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         5.6400e+00],
        [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
         6.4800e+00],
        [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
         7.8800e+00]]),
 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
        18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
        15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
        13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
        21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
        35.4, 24.7, 3

In [160]:
features = pd.DataFrame(boston.data, columns=boston.feature_names)

In [161]:
features.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [162]:
targets = boston.target
targets

array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 18.7, 16. , 22.2, 25. , 33. , 23.5,
       19.4, 22. , 17.4, 20.9, 24.2, 21.7, 22.8, 23.4, 24.1, 21.4, 20. ,
       20.8, 21.2, 20.3, 28. , 23.9, 24.8, 22.9, 23.9, 26.6, 22.5, 22.2,
       23.6, 28.7, 22.6, 22. , 22.9, 25. , 20.6, 28.4, 21.4, 38.7, 43.8,
       33.2, 27.5, 26.5, 18.6, 19.3, 20.1, 19.5, 19.5, 20.4, 19.8, 19.4,
       21.7, 22.8, 18.8, 18.7, 18.5, 18.3, 21.2, 19.2, 20.4, 19.3, 22. ,
       20.3, 20.5, 17.3, 18.8, 21.4, 15.7, 16.2, 18. , 14.3, 19.2, 19.6,
       23. , 18.4, 15.6, 18.1, 17.4, 17.1, 13.3, 17.8, 14. , 14.4, 13.4,
       15.6, 11.8, 13.8, 15.6, 14.6, 17.8, 15.4, 21

In [163]:
import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier, BaggingRegressor, RandomForestRegressor

In [164]:
features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
dtypes: float64(13)
memory usage: 51.4 KB


In [165]:
X = features
y = targets

In [166]:
lab_enc = preprocessing.LabelEncoder()
training_scores_encoded = lab_enc.fit_transform(y)

In [168]:
training_scores_encoded

array([137, 113, 196, 193, 203, 165, 126, 156,  64,  87,  52,  87, 114,
       102,  80,  97, 128,  73, 100,  80,  40,  94,  54,  48,  57,  42,
        65,  50,  82, 108,  32,  48,  36,  35,  39,  87,  98, 108, 144,
       176, 197, 153, 149, 144, 110,  91,  98,  65,  47,  92,  95, 103,
       146, 131,  87, 200, 144, 181, 130,  94,  85,  59, 119, 146, 189,
       132,  92, 117,  72, 107, 139, 114, 125, 131, 138, 111,  98, 106,
       110, 101, 159, 136, 145, 126, 136, 153, 122, 119, 133, 165, 123,
       117, 126, 146, 104, 162, 111, 211, 219, 191, 157, 152,  84,  91,
        99,  93,  93, 102,  96,  92, 114, 125,  86,  85,  83,  81, 110,
        90, 102,  91, 117, 101, 103,  71,  86, 111,  58,  61,  78,  46,
        90,  94, 127,  82,  57,  79,  72,  69,  37,  76,  43,  47,  38,
        57,  25,  41,  57,  49,  76,  56, 112,  94,  55,  92,  68,  57,
        35, 213, 140, 130, 155, 228, 228, 228, 124, 146, 228, 135, 135,
       120,  72,  89, 128, 133, 123, 168, 129, 143, 171, 207, 21

In [169]:
print(utils.multiclass.type_of_target(y))
print(utils.multiclass.type_of_target(y.astype('int')))
print(utils.multiclass.type_of_target(training_scores_encoded))

continuous
multiclass
multiclass


In [170]:
X_train, X_test, y_train, y_test = train_test_split(X, training_scores_encoded, train_size=0.5, random_state=0)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2179: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [171]:
rfc1 = RandomForestClassifier(max_features=10, random_state=1)

In [172]:
rfc1.fit(X_train, y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features=10, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=None,
            oob_score=False, random_state=1, verbose=0, warm_start=False)

In [ ]:
sklearn.metrics.roc_auc_score(y_true, y_score, average=’macro’, sample_weight=None)

In [181]:
pred1 = rfc1.predict(X_test)
print(pred1.shape)
pred1

(253,)


array([ 91,  94, 165,   4, 114, 102, 115,  88,  55,  88,   3,  28,  60,
         0, 228, 145,  89, 173, 171,  87, 128, 120,  99,  87, 144,  28,
        80,  56, 133,  81,  44,  93,  74,  95, 143,  56,   0,  42,  89,
        89, 114, 110, 104,  89, 117, 117, 131,  24,  49,  99,  35, 115,
       123, 214,  37, 114,  92,  74,  38, 121,  80, 114,  80, 180,  89,
       197,  76,  87,  89,  87, 104, 106, 117, 136, 146,  12, 209, 122,
       117,  67, 172,  90,   0, 209, 214, 146, 191,  89, 146,  44, 126,
        34, 117, 173, 117,  74,  41, 126,  63,  95, 146,  99, 157, 144,
       114,  87,  10, 106, 117, 145, 146,   0,  87,  81,   3,  73,  10,
        94,  22, 228, 119,  22,  47,  67, 123,  71, 161,  74,  95, 190,
        76,  34,   3,  67,  34, 117, 128,  57, 180,  34,  42, 115, 186,
       131, 101,  42, 197, 202,   2,  16, 135, 176,  46, 119,  76,  80,
       101,  35, 117,  35,   8, 102, 158, 180,  74,  87, 128, 126, 146,
         4, 178,  10,  67, 146, 115,   4, 115,  89, 123,  95,  6